# Regenerates the workbench impact map's land: python3 tools/bench-map.py land-50m.json land-10m.json > assets/js/bench-map.js
# (land-*.json from https://cdn.jsdelivr.net/npm/world-atlas@2/, Natural Earth, public domain)
# Two projections, both equirectangular scaled for ~25°N, matching bench.js (MAP and INSET there):
#   main:  Türkiye to Korea, viewBox 0 0 1000 500
#   inset: the Gulf, enlarged, drawn in the bottom-left corner over the Horn of Africa
import json, sys

def decode(path):
    t = json.load(open(path))
    sx, sy = t["transform"]["scale"]; tx, ty = t["transform"]["translate"]
    arcs = []
    for a in t["arcs"]:
        x = y = 0; pts = []
        for dx, dy in a:
            x += dx; y += dy; pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)
    def arc(i): return arcs[i] if i >= 0 else arcs[~i][::-1]
    def ring(r):
        out = []
        for i in r:
            p = arc(i); out.extend(p if not out else p[1:])
        return out
    for g in t["objects"]["land"]["geometries"]:
        for poly in (g["arcs"] if g["type"] == "MultiPolygon" else [g["arcs"]]):
            for r in poly: yield ring(r)

def build(rings, proj, box, keep_px):
    BX0, BY0, BX1, BY1 = box
    d = []
    for pts in rings:
        pp = [proj(x, y) for x, y in pts]
        if all(px < BX0 for px, _ in pp) or all(px > BX1 for px, _ in pp) or all(py < BY0 for _, py in pp) or all(py > BY1 for _, py in pp): continue
        pp = [(min(max(px, BX0), BX1), min(max(py, BY0), BY1)) for px, py in pp]
        keep = [pp[0]]
        for q in pp[1:]:
            if abs(q[0] - keep[-1][0]) + abs(q[1] - keep[-1][1]) > keep_px: keep.append(q)
        if len(keep) < 3: continue
        xs = [q[0] for q in keep]; ys = [q[1] for q in keep]
        if max(xs) - min(xs) < 1.5 and max(ys) - min(ys) < 1.5: continue
        d.append("M" + "L".join("%.1f %.1f" % q for q in keep) + "Z")
    return "".join(d)

MAIN = lambda lon, lat: ((lon - 24) * 9.06, (46 - lat) * 10)
IX, IY = 10, 344
INSET = lambda lon, lat: (IX + (lon - 47.8) * 27, IY + (28.6 - lat) * 29.8)
main = build(decode(sys.argv[1]), MAIN, (-8, -8, 1008, 508), 1.8)
inset = build(decode(sys.argv[2]), INSET, (IX - 6, IY - 6, IX + 265 + 6, IY + 152 + 6), 1.0)
print("/* Generated by tools/bench-map.py from Natural Earth (public domain). Do not edit. */")
print("window.BENCH_MAP = " + json.dumps({"main": main, "inset": inset}) + ";")
